services:
  snapserver:
    image: ghcr.io/sweisgerber/snapcast:latest
    environment:
      - PUID=1000
      - PGID=1000 # set to audio group ID
      - TZ=Europe/Zurich
    networks:
      snapcast-ipvlan:
        ipv4_address: 192.168.0.20
      sound-server:
    volumes:
      - snapcast-fifos:/audio/
      - /etc/sound-server/snapserver.conf/:/config/snapserver.conf:ro
      - snapcast-data:/data/

  mopidy:
    image: ghcr.io/sweisgerber/mopidy:latest
    # image: jaedb/iris
    environment:
      - PUID=33 # user ID which the mopidy service will run as, needs permissions to access the music
      - PGID=33 # group ID which the mopidy service will run as, needs permissions to access the music
      - TZ=Europe/Zurich
      # - DOCKER_MODS=linuxserver/mods:universal-package-install
      # - INSTALL_PIP_PACKAGES=Mopidy-TuneIn
      # - INSTALL_PACKAGES=gst-plugins-bad
    ports:
      - 6600:6600/tcp # MPD port
      - 6680:6680/tcp # Mopidy Web Interface
    networks:
      - sound-server
    healthcheck:
      test: curl -f http://localhost:6680/iris/http/get_config || exit 1
      timeout: 5s
      retries: 5
    volumes:
      - iris-data:/data/ 
      - /etc/sound-server/mopidy.conf:/config/mopidy.conf
      - snapcast-fifos:/tmp/snapcast-fifos
  
  beets:
    image: lscr.io/linuxserver/beets:latest
    environment:
      - PUID=33
      - PGID=33
      - TZ=Europe/Zurich
    volumes:
      - /etc/sound-server/beets-config.yaml:/config/config.yaml:ro
      - /var/lib/sound-server/beets:/config/data # holds the log file and the database
      - /srv/nc-data-no-bkp/Music:/music
      - /srv/nc-data-no-bkp/Music/Upload:/downloads
    ports:
      - 8337:8337
    networks:
      - sound-server
    restart: unless-stopped

networks:
  sound-server:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: sound-server
    name: sound-server
  snapcast-ipvlan:
    driver: ipvlan
    driver_opts:
      parent: enp0s31f6
      # to enable mDNS (which advertises the Spotify Connect service), the container must receive Multicast packets
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

volumes:
  snapcast-fifos:
  snapcast-data:
  iris-data:
